<?php
/*********************************************************
 * 错误码列表
 *
 * @author  Lujia
 * @version 1.0 by Lujia @ 2013.12.23 创建错误列表
 ***********************************************************/

$_error_code = array(
        10 => array(
            // 基本错误码
            'MSG_SUCCESS'                           => array('10000', '成功'),
            'MSG_ERR_LESS_PARAM'                    => array('10001', '请求缺少必要的参数'),
            'MSG_ERR_FAIL_PARAM'                    => array('10002', '请求参数错误'),
            'MSG_ERR_FAIL_SIGN'                     => array('10003', '签名验证错误'),
            'MSG_ERR_FAIL_SEARCH'                   => array('10004', '查询结果为空'),
            
            // 用户相关错误码
            'MSG_ERR_TOKEN'                         => array('20001', 'TOKEN验证错误'),
            'MSG_ERR_USERNAME_SET'                  => array('20002', '用户名已经设定过，不可再次修改'),
            'MSG_ERR_USERNAME_EXIST'                => array('20003', '用户名已经存在'),
            'MSG_ERR_EMAIL_EXIST'                   => array('20004', '邮箱已经存在'),
            'MSG_ERR_MOBILE_EXIST'                  => array('20005', '手机号码已经存在'),
            'MSG_ERR_PASSWORD_HASSET'               => array('20006', '您已设定密码'),
            'MSG_ERR_PASSWORD_WRONG'                => array('20007', '您输入的密码错误'),
            'MSG_ERR_USER_BAN'                      => array('20008', '您已被禁止登入'),
            'MSG_ERR_NO_USER'                       => array('20009', '用户不存在'),
            'MSG_ERR_REJECT_FRIEND'                 => array('20010', '对方拒绝接收好友请求'),
            'MSG_ERR_ALEADY_FRIEND'                 => array('20011', '对方已经是你的好友了'),
            'MSG_ERR_NO_FRIEND_REQ'                 => array('20012', '无此好友请求'),
            'MSG_ERR_SHIELD_WORD'                   => array('20013', '用户名中含有屏蔽词'),
            'MSG_ERR_UPLOAD_HEAD_IMG'               => array('20014', '用户上传头像失败'),
            'MSG_ERR_MOBILE_INPUT'                  => array('20015', '手机格式不正确'),
            'MSG_ERR_EMAIL_INPUT'                   => array('20016', '邮箱格式不正确'),
            'MSG_ERR_ADD_SELF_FRIEND'               => array('20017', '不能添加自己为好友'),
            'MSG_ERR_USERINFO_NOT_MAKE_CHANES'      => array('20018', '用户信息未做修改'),
            'MSG_ERR_SET_SAME_PASSWORD'             => array('20019', '用户名不能与密码相同'),
            'MSG_ERR_NO_FRIEND'                     => array('20020', '未建立好友关系'),
            'MSG_ERR_EMAIL_FAIL'                    => array('20021', '邮箱验证错误'),
            'MSG_ERR_USERNAME_LENGTH'               => array('20022', '用户名长度错误，只能6到14位字符'),
            'MSG_ERR_USERNAME_WORD'                 => array('20023', '用户名包含敏感词，不能注册。'),
            'MSG_ERR_USERNAME_NO'                   => array('20024', '用户名只能修改一次。'),
            'MSG_ERR_UPLOAD_IMG_ERR'                => array('20025', '您上传头像不是照片请正确上传'),
            'MSG_ERR_PASSWORD_ERR'	                 => array('20026', '系统用户，不能登录'),
            'MSG_ERR_CONTENT_ERR'                   => array('20027', '意见返回内容不能少于5个字'),
            'MSG_ERR_MONEY'                         => array('20028', '人民币不能为负值'),
            'MSG_ISO_PAY_WRONG'                     => array('20029', '支付验证错误'),
            'MSG_ISO_PAY_FAIL'                      => array('20030', '支付验证失败'),
            'MSG_ISO_PAY_OK'                        => array('20031', '支付验证成功'),
            'MSG_ERR_UNSET_PASSWORD'                => array('20032', '您还未绑定账号'),
            'MSG_ERR_EDIT_PASSWORD_LOGIN'           => array('20033', '您的账号已经修改密码，请登录或重新注册账号'),
            'MSG_ERR_SOFTWARE_OFF'                  => array('20034', '渠道已关闭'),
            'MSG_ERR_PASSWORD_INPIT'                => array('20035', '密码格式不正确'),
            'MSG_ERR_NIKENAME_LENGTH'               => array('20036', '用户昵称长度错误，只能6到14位字符'),
            'MSG_ERR_NEW_PASSWORD'                  => array('20037', '两次密码不相同，请修改'),
                
            'MSG_ERR_EVERY_ACCEPT_VIT'              => array('20041', '您每日接收好友赠送体力次数已到上限'),
            'MSG_ERR_GIVE_VIT_COUNT'                => array('20042', '您每日赠送好友体力次数已到上限'),
            'MSG_ERR_ADD_FRIEND_NUM'                => array('20043', '您添加好友的数量超过上限不能继续添加'),
            'MSG_ERR_FULL_VIT'                      => array('20044', '您的体力已满，不能接受体力'),
            
            //GODDESS
            'MSG_ERR_NO_GIFT'                     => array('40001', '无此礼物或该礼物不可用'),
            'MSG_ERR_CHAKRA_DEFICIENCY'           => array('40002', '您的体力值不足'),
            'MSG_ERR_NO_FOLLOW'                   => array('40003', '您还没有追求这个女神'),
            'MSG_ERR_NO_EXIST_GODDESS'            => array('40004', '这个女神不存在'),
            'MSG_ERR_FAIL_MESS'                   => array('40005', '未找到这条消息'),
            'MSG_ERR_NO_FOUND_IMG'                => array('40006', '未找到图片信息'),
            'MSG_ERR_NO_UNLOCK_IMG'               => array('40007', '照片还没有解锁'),
            'MSG_ERR_FAIL_PRAISED'                => array('40008', '您已赞过'),
            'MSG_ERR_FAIL_UPGRADE'                => array('40009', '已经是最新版本'),
            'MSG_ERR_FAIL_UNLOCKED'               => array('40010', '该照片已经解锁过'),
            'MSG_ERR_FAIL_DAILY'                  => array('40011', '今天已经送过经验了'),
            'MSG_ERR_FAIL_GIVINGVIT'              => array('40012', '今天已经送过体力了'),
            'MSG_ERR_NO_FOUND_P_INFO'             => array('40013', '未找到您的注册信息'),
            'MSG_ERR_NO_FOUND_TAG'                => array('40014', '未找到此标签'),
            'MSG_ERR_NO_GET_LOGIN_REWARD'         => array('40015', '不能领取'),
            'MSG_ERR_LOGIN_REWARD_OK'             => array('40016', '奖励已经领取'),
            'MSG_ERR_EARN_GAME_REWARD'            => array('40017', '您已领过金币，不能重复领取'),
            'MSG_ERR_GUESS_EXIST'                 => array('40019', '您已获取奖励，不能重复获取'),
            'MSG_ERR_LIKING_NO_GUESS'             => array('40020', '您与女神好感值不够,不能继续游戏'),
            'MSG_ERR_GUESS_NO_WIPE'               => array('40021', '猜图不中次数不到5次，不能参加擦牌'),
            'MSG_ERR_HAVE_TERMS'                  => array('40022', '女神没有前置条件，可以直接解锁'),
            'MSG_ERR_UNLOCK_GODDESS_TERMS'        => array('40023', '未达到女神解锁条件，不能解锁。'),
            'MSG_ERR_NO_GOLD'                     => array('40024', '解锁女神所需金币不足'),
            'MSG_ERR_NO_SEARCH_EARN_GOLD'         => array('40025', '查询结果错误 ,没有找到翻牌结果。'),
            'MSG_ERR_VIT_FULL'                    => array('40026', '体力已满，不需要购买。'),
            'MSG_ERR_SOFTWARE_TO_GOLD'            => array('40027', '推荐软件金币已经领取，不能重复领取'),
            'MSG_ERR_NO_UNLOCK_GODDESS'           => array('40028', '已解锁过前置条件，不能重复解锁。'),
            'MSG_ERR_UNLOCK_GODDESS_GOLD'         => array('40029', '您的金币不够，不能解锁。'),
            
            // 其它
            'MSG_ERR_UNKOWN'                      => array('99999', '系统繁忙，请稍后再试'),
        ),
        //下限少女
        11 => array(
                // 基本错误码
                'MSG_SUCCESS'                           => array('10000', '成功'),
                'MSG_ERR_LESS_PARAM'                    => array('10001', '请求缺少必要的参数'),
                'MSG_ERR_FAIL_PARAM'                    => array('10002', '请求参数错误'),
                'MSG_ERR_FAIL_SIGN'                     => array('10003', '签名验证错误'),
                'MSG_ERR_FAIL_SEARCH'                   => array('10004', '查询结果为空'),
        
                // 用户相关错误码
                'MSG_ERR_TOKEN'                         => array('20001', 'TOKEN验证错误'),
                'MSG_ERR_USERNAME_SET'                  => array('20002', '用户名已经设定过，不可再次修改'),
                'MSG_ERR_USERNAME_EXIST'                => array('20003', '用户名已经存在'),
                'MSG_ERR_EMAIL_EXIST'                   => array('20004', '邮箱已经存在'),
                'MSG_ERR_MOBILE_EXIST'                  => array('20005', '手机号码已经存在'),
                'MSG_ERR_PASSWORD_HASSET'               => array('20006', '您已设定密码'),
                'MSG_ERR_PASSWORD_WRONG'                => array('20007', '您输入的密码错误'),
                'MSG_ERR_USER_BAN'                      => array('20008', '您已被禁止登入'),
                'MSG_ERR_NO_USER'                       => array('20009', '用户不存在'),
                'MSG_ERR_REJECT_FRIEND'                 => array('20010', '对方拒绝接收好友请求'),
                'MSG_ERR_ALEADY_FRIEND'                 => array('20011', '对方已经是你的好友了'),
                'MSG_ERR_NO_FRIEND_REQ'                 => array('20012', '无此好友请求'),
                'MSG_ERR_SHIELD_WORD'                   => array('20013', '用户名中含有屏蔽词'),
                'MSG_ERR_UPLOAD_HEAD_IMG'               => array('20014', '用户上传头像失败'),
                'MSG_ERR_MOBILE_INPUT'                  => array('20015', '手机格式不正确'),
                'MSG_ERR_EMAIL_INPUT'                   => array('20016', '邮箱格式不正确'),
                'MSG_ERR_ADD_SELF_FRIEND'               => array('20017', '不能添加自己为好友'),
                'MSG_ERR_USERINFO_NOT_MAKE_CHANES'      => array('20018', '用户信息未做修改'),
                'MSG_ERR_SET_SAME_PASSWORD'             => array('20019', '用户名不能与密码相同'),
                'MSG_ERR_NO_FRIEND'                     => array('20020', '未建立好友关系'),
                'MSG_ERR_EMAIL_FAIL'                    => array('20021', '邮箱验证错误'),
                'MSG_ERR_USERNAME_LENGTH'               => array('20022', '用户名长度错误，只能6到14位字符'),
                'MSG_ERR_USERNAME_WORD'                 => array('20023', '用户名包含敏感词，不能注册。'),
                'MSG_ERR_USERNAME_NO'                   => array('20024', '用户名只能修改一次。'),
                'MSG_ERR_UPLOAD_IMG_ERR'                => array('20025', '您上传头像不是照片请正确上传'),
                'MSG_ERR_PASSWORD_ERR'	                => array('20026', '系统用户，不能登录'),
                'MSG_ERR_CONTENT_ERR'                   => array('20027', '意见返回内容不能少于5个字'),
                'MSG_ERR_MONEY'                         => array('20028', '人民币不能为负值'),
                'MSG_ISO_PAY_WRONG'                     => array('20029', '支付验证错误'),
                'MSG_ISO_PAY_FAIL'                      => array('20030', '支付验证失败'),
                'MSG_ISO_PAY_OK'                        => array('20031', '支付验证成功'),
                'MSG_ERR_UNSET_PASSWORD'                => array('20032', '您还未绑定账号'),
                'MSG_ERR_EDIT_PASSWORD_LOGIN'           => array('20033', '您的账号已经修改密码，请登录或重新注册账号'),
                'MSG_ERR_SOFTWARE_OFF'                  => array('20034', '渠道已关闭'),
                'MSG_ERR_PASSWORD_INPIT'                => array('20035', '密码格式不正确'),
                'MSG_ERR_NIKENAME_LENGTH'               => array('20036', '用户昵称长度错误，只能6到14位字符'),
                'MSG_ERR_NEW_PASSWORD'                  => array('20037', '两次密码不相同，请修改'),
                
                'MSG_ERR_EVERY_ACCEPT_VIT'              => array('20041', '您每日接收好友赠送体力次数已到上限'),
                'MSG_ERR_GIVE_VIT_COUNT'                => array('20042', '您每日赠送好友体力次数已到上限'),
                'MSG_ERR_ADD_FRIEND_NUM'                => array('20043', '您添加好友的数量超过上限不能继续添加'),
                'MSG_ERR_FULL_VIT'                      => array('20044', '您的体力已满，不能接受体力'),
        
                //GODDESS
                'MSG_ERR_NO_GIFT'                     => array('40001', '无此礼物或该礼物不可用'),
                'MSG_ERR_CHAKRA_DEFICIENCY'           => array('40002', '您的体力值不足'),
                'MSG_ERR_NO_FOLLOW'                   => array('40003', '您还没有追求这个妹子'),
                'MSG_ERR_NO_EXIST_GODDESS'            => array('40004', '这个妹子不存在'),
                'MSG_ERR_FAIL_MESS'                   => array('40005', '未找到这条消息'),
                'MSG_ERR_NO_FOUND_IMG'                => array('40006', '未找到图片信息'),
                'MSG_ERR_NO_UNLOCK_IMG'               => array('40007', '图片还没有解锁'),
                'MSG_ERR_FAIL_PRAISED'                => array('40008', '您已赞过'),
                'MSG_ERR_FAIL_UPGRADE'                => array('40009', '已经是最新版本'),
                'MSG_ERR_FAIL_UNLOCKED'               => array('40010', '该图片已经解锁过'),
                'MSG_ERR_FAIL_DAILY'                  => array('40011', '今天已经送过经验了'),
                'MSG_ERR_FAIL_GIVINGVIT'              => array('40012', '今天已经送过体力了'),
                'MSG_ERR_NO_FOUND_P_INFO'             => array('40013', '未找到您的注册信息'),
                'MSG_ERR_NO_FOUND_TAG'                => array('40014', '未找到此标签'),
                'MSG_ERR_NO_GET_LOGIN_REWARD'         => array('40015', '不能领取'),
                'MSG_ERR_LOGIN_REWARD_OK'             => array('40016', '奖励已经领取'),
                'MSG_ERR_EARN_GAME_REWARD'            => array('40017', '您已领过金币，不能重复领取'),
                'MSG_ERR_GUESS_EXIST'                 => array('40019', '您已获取奖励，不能重复获取'),
                'MSG_ERR_LIKING_NO_GUESS'             => array('40020', '您与妹子好感值不够,不能继续游戏'),
                'MSG_ERR_GUESS_NO_WIPE'               => array('40021', '猜图不中次数不到5次，不能参加擦牌'),
                'MSG_ERR_HAVE_TERMS'                  => array('40022', '妹子没有前置条件，可以直接解锁'),
                'MSG_ERR_UNLOCK_GODDESS_TERMS'        => array('40023', '未达到妹子解锁条件，不能解锁。'),
                'MSG_ERR_NO_GOLD'                     => array('40024', '解锁妹子所需金币不足'),
                'MSG_ERR_NO_SEARCH_EARN_GOLD'         => array('40025', '查询结果错误 ,没有找到翻牌结果。'),
                'MSG_ERR_VIT_FULL'                    => array('40026', '体力已满，不需要购买。'),
                'MSG_ERR_SOFTWARE_TO_GOLD'            => array('40027', '推荐软件金币已经领取，不能重复领取'),
                'MSG_ERR_NO_UNLOCK_GODDESS'           => array('40028', '已解锁过前置条件，不能重复解锁。'),
                'MSG_ERR_UNLOCK_GODDESS_GOLD'         => array('40029', '您的金币不够，不能解锁。'),
        
                // 其它
                'MSG_ERR_UNKOWN'                      => array('99999', '系统繁忙，请稍后再试'),
        ),
        //二次元私密
        12 => array(
                // 基本错误码
                'MSG_SUCCESS'                           => array('10000', '成功'),
                'MSG_ERR_LESS_PARAM'                    => array('10001', '请求缺少必要的参数'),
                'MSG_ERR_FAIL_PARAM'                    => array('10002', '请求参数错误'),
                'MSG_ERR_FAIL_SIGN'                     => array('10003', '签名验证错误'),
                'MSG_ERR_FAIL_SEARCH'                   => array('10004', '查询结果为空'),
        
                // 用户相关错误码
                'MSG_ERR_TOKEN'                         => array('20001', 'TOKEN验证错误'),
                'MSG_ERR_USERNAME_SET'                  => array('20002', '用户名已经设定过，不可再次修改'),
                'MSG_ERR_USERNAME_EXIST'                => array('20003', '用户名已经存在'),
                'MSG_ERR_EMAIL_EXIST'                   => array('20004', '邮箱已经存在'),
                'MSG_ERR_MOBILE_EXIST'                  => array('20005', '手机号码已经存在'),
                'MSG_ERR_PASSWORD_HASSET'               => array('20006', '您已设定密码'),
                'MSG_ERR_PASSWORD_WRONG'                => array('20007', '您输入的密码错误'),
                'MSG_ERR_USER_BAN'                      => array('20008', '您已被禁止登入'),
                'MSG_ERR_NO_USER'                       => array('20009', '用户不存在'),
                'MSG_ERR_REJECT_FRIEND'                 => array('20010', '对方拒绝接收好友请求'),
                'MSG_ERR_ALEADY_FRIEND'                 => array('20011', '对方已经是你的好友了'),
                'MSG_ERR_NO_FRIEND_REQ'                 => array('20012', '无此好友请求'),
                'MSG_ERR_SHIELD_WORD'                   => array('20013', '用户名中含有屏蔽词'),
                'MSG_ERR_UPLOAD_HEAD_IMG'               => array('20014', '用户上传头像失败'),
                'MSG_ERR_MOBILE_INPUT'                  => array('20015', '手机格式不正确'),
                'MSG_ERR_EMAIL_INPUT'                   => array('20016', '邮箱格式不正确'),
                'MSG_ERR_ADD_SELF_FRIEND'               => array('20017', '不能添加自己为好友'),
                'MSG_ERR_USERINFO_NOT_MAKE_CHANES'      => array('20018', '用户信息未做修改'),
                'MSG_ERR_SET_SAME_PASSWORD'             => array('20019', '用户名不能与密码相同'),
                'MSG_ERR_NO_FRIEND'                     => array('20020', '未建立好友关系'),
                'MSG_ERR_EMAIL_FAIL'                    => array('20021', '邮箱验证错误'),
                'MSG_ERR_USERNAME_LENGTH'               => array('20022', '用户名长度错误，只能6到14位字符'),
                'MSG_ERR_USERNAME_WORD'                 => array('20023', '用户名包含敏感词，不能注册。'),
                'MSG_ERR_USERNAME_NO'                   => array('20024', '用户名只能修改一次。'),
                'MSG_ERR_UPLOAD_IMG_ERR'                => array('20025', '您上传头像不是照片请正确上传'),
                'MSG_ERR_PASSWORD_ERR'	                => array('20026', '系统用户，不能登录'),
                'MSG_ERR_CONTENT_ERR'                   => array('20027', '意见返回内容不能少于5个字'),
                'MSG_ERR_MONEY'                         => array('20028', '人民币不能为负值'),
                'MSG_ISO_PAY_WRONG'                     => array('20029', '支付验证错误'),
                'MSG_ISO_PAY_FAIL'                      => array('20030', '支付验证失败'),
                'MSG_ISO_PAY_OK'                        => array('20031', '支付验证成功'),
                'MSG_ERR_UNSET_PASSWORD'                => array('20032', '您还未绑定账号'),
                'MSG_ERR_EDIT_PASSWORD_LOGIN'           => array('20033', '您的账号已经修改密码，请登录或重新注册账号'),
                'MSG_ERR_SOFTWARE_OFF'                  => array('20034', '渠道已关闭'),
                'MSG_ERR_PASSWORD_INPIT'                => array('20035', '密码格式不正确'),
                'MSG_ERR_NIKENAME_LENGTH'               => array('20036', '用户昵称长度错误，只能6到14位字符'),
                'MSG_ERR_NEW_PASSWORD'                  => array('20037', '两次密码不相同，请修改'),
                
                'MSG_ERR_EVERY_ACCEPT_VIT'              => array('20041', '您每日接收好友赠送体力次数已到上限'),
                'MSG_ERR_GIVE_VIT_COUNT'                => array('20042', '您每日赠送好友体力次数已到上限'),
                'MSG_ERR_ADD_FRIEND_NUM'                => array('20043', '您添加好友的数量超过上限不能继续添加'),
                'MSG_ERR_FULL_VIT'                      => array('20044', '您的体力已满，不能接受体力'),
        
                //GODDESS
                'MSG_ERR_NO_GIFT'                     => array('40001', '无此礼物或该礼物不可用'),
                'MSG_ERR_CHAKRA_DEFICIENCY'           => array('40002', '您的体力值不足'),
                'MSG_ERR_NO_FOLLOW'                   => array('40003', '您还没有追求这个美女'),
                'MSG_ERR_NO_EXIST_GODDESS'            => array('40004', '这个美女不存在'),
                'MSG_ERR_FAIL_MESS'                   => array('40005', '未找到这条消息'),
                'MSG_ERR_NO_FOUND_IMG'                => array('40006', '未找到图片信息'),
                'MSG_ERR_NO_UNLOCK_IMG'               => array('40007', '图片还没有解锁'),
                'MSG_ERR_FAIL_PRAISED'                => array('40008', '您已赞过'),
                'MSG_ERR_FAIL_UPGRADE'                => array('40009', '已经是最新版本'),
                'MSG_ERR_FAIL_UNLOCKED'               => array('40010', '该图片已经解锁过'),
                'MSG_ERR_FAIL_DAILY'                  => array('40011', '今天已经送过经验了'),
                'MSG_ERR_FAIL_GIVINGVIT'              => array('40012', '今天已经送过体力了'),
                'MSG_ERR_NO_FOUND_P_INFO'             => array('40013', '未找到您的注册信息'),
                'MSG_ERR_NO_FOUND_TAG'                => array('40014', '未找到此标签'),
                'MSG_ERR_NO_GET_LOGIN_REWARD'         => array('40015', '不能领取'),
                'MSG_ERR_LOGIN_REWARD_OK'             => array('40016', '奖励已经领取'),
                'MSG_ERR_EARN_GAME_REWARD'            => array('40017', '您已领过金币，不能重复领取'),
                'MSG_ERR_GUESS_EXIST'                 => array('40019', '您已获取奖励，不能重复获取'),
                'MSG_ERR_LIKING_NO_GUESS'             => array('40020', '您与美女好感值不够,不能继续游戏'),
                'MSG_ERR_GUESS_NO_WIPE'               => array('40021', '猜图不中次数不到5次，不能参加擦牌'),
                'MSG_ERR_HAVE_TERMS'                  => array('40022', '美女没有前置条件，可以直接解锁'),
                'MSG_ERR_UNLOCK_GODDESS_TERMS'        => array('40023', '未达到美女解锁条件，不能解锁。'),
                'MSG_ERR_NO_GOLD'                     => array('40024', '解锁美女所需金币不足'),
                'MSG_ERR_NO_SEARCH_EARN_GOLD'         => array('40025', '查询结果错误 ,没有找到翻牌结果。'),
                'MSG_ERR_VIT_FULL'                    => array('40026', '体力已满，不需要购买。'),
                'MSG_ERR_SOFTWARE_TO_GOLD'            => array('40027', '推荐软件金币已经领取，不能重复领取'),
                'MSG_ERR_NO_UNLOCK_GODDESS'           => array('40028', '已解锁过前置条件，不能重复解锁。'),
                'MSG_ERR_UNLOCK_GODDESS_GOLD'         => array('40029', '您的金币不够，不能解锁。'),
        
                // 其它
                'MSG_ERR_UNKOWN'                      => array('99999', '系统繁忙，请稍后再试'),
        )
        
);

// return $ErrorCode;
